(()=>{
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const canvas=document.getElementById('network'),ctx=canvas.getContext('2d');
 const portrait=document.querySelector('.portrait-wrap'),hero=document.querySelector('.hero');
 const pointer={x:0,y:0};let w=0,h=0,frame=0,last=0,t=0,inside=true;
 function draw(){if(!ctx)return;ctx.clearRect(0,0,w,h);const cols=16,rows=9,points=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)points.push({x:x*w/(cols-1)+Math.cos(y*.8+t)*8+pointer.x*7,y:y*h/(rows-1)+Math.sin(x*.55+y*.6+t)*12+pointer.y*6});ctx.lineWidth=.65;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const p=points[y*cols+x];ctx.strokeStyle='rgba(110,133,163,.13)';for(const n of [x<cols-1?points[y*cols+x+1]:null,y<rows-1?points[(y+1)*cols+x]:null]){if(n){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(n.x,n.y);ctx.stroke()}}if((x+y)%4===0){ctx.fillStyle='rgba(100,128,165,.3)';ctx.beginPath();ctx.arc(p.x,p.y,1.5,0,Math.PI*2);ctx.fill()}}}
 function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;if(ctx)ctx.setTransform(d,0,0,d,0,0);draw()}
 // Subtle continuous motion while visible; respect the visitor’s system motion preference.
 function loop(now){frame=0;if(reduced.matches||document.hidden||!inside)return;const dt=last?Math.min(now-last,50):16;last=now;t+=dt*.00012;draw();frame=requestAnimationFrame(loop)}
 function sync(){cancelAnimationFrame(frame);last=0;document.body.classList.toggle('motion-paused',reduced.matches);document.documentElement.style.scrollBehavior=reduced.matches?'auto':'';if(reduced.matches)portrait.style.transform='';if(!reduced.matches&&!document.hidden&&inside)frame=requestAnimationFrame(loop);else draw()}
 reduced.addEventListener('change',sync);document.addEventListener('visibilitychange',sync);
 if('IntersectionObserver' in window){new IntersectionObserver(es=>{inside=es[0].isIntersecting;sync()}).observe(hero);const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.section-heading,.project,.story-intro,.timeline article,.education,.skills>div,.research-note,.contact h2').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
 hero.addEventListener('pointermove',e=>{if(reduced.matches||e.pointerType==='touch')return;const r=hero.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width-.5;pointer.y=(e.clientY-r.top)/r.height-.5;portrait.style.transform=`rotateY(${pointer.x*4}deg) rotateX(${-pointer.y*3}deg)`;if(elapsed>=4000)draw()});hero.addEventListener('pointerleave',()=>{pointer.x=pointer.y=0;portrait.style.transform='';draw()});
 const progress=document.querySelector('.scroll-progress');let scrollFrame=0;function updateProgress(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?scrollY/max:0})`;scrollFrame=0}addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateProgress)},{passive:true});addEventListener('resize',()=>{resize();updateProgress()});resize();sync();updateProgress();
})();
